name = "oolong"
version = "0.1.0"
license = "BSD 3-Clause"
author = "Ed Hone"
copyright = "Copyright 2024, Ed Hone"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
[preprocess.cpp]

[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive"}