name: pull-request

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install build dependencies
      - name: Install build dependencies
        if: ${{ matrix.build == 'fpm' }}
        uses: fortran-lang/setup-fpm@v3
        with:
          fpm-version: 'v0.8.0'

      # Build oolong
      - name: Build Oolong with FPM
        run: fpm build

      # Run tests
      - name: Test Oolong with FPM
        run: fpm test